services:
  - type: web
    name: farming-marketplace
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
