services:
  - type: web
    name: farming-marketplace
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000
    disk:
      name: cache
      sizeGB: 1
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /_next/static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /_next/image*
        name: Cache-Control
        value: public, max-age=60
